### ISSUE TITLE
hello can we work together

### ISSUE THREAD

**Issue by la-niina** [dev7dev/V2ray-Android#1]
Hello am la niina aka mxbhaee the developer of NamelessnetR v2ray and NamelessnetX v2ray all bought , but have an idea of making an upgrade in design and core with additional features . But its tiresome working alone and you code is real good and would wish to work with you to make something real nice .

**Comment by dev7dev** [comment]
Hi
You can contact me through the email below:
dev7developers@gmail.com

thanks for your attention

**Comment by dev7dev** [comment]
> Hello am la niina aka mxbhaee the developer of NamelessnetR v2ray and NamelessnetX v2ray all bought , but have an idea of making an upgrade in design and core with additional features . But its tiresome working alone and you code is real good and would wish to work with you to make something real nice .

Hi
You can contact me through the email below:
[dev7developers@gmail.com](mailto:dev7developers@gmail.com)

thanks for your attention
