### ISSUE TITLE
Added Uri support

### ISSUE THREAD

**Issue by codewithtamim** [dev7dev/V2ray-Android#12]
Hey bro I have added uri support in the app and it supports direct uri links such as vmess,vless,trojan .
I don't know much about github I'm new here. How can I upload the code ?

**Comment by dev7dev** [comment]
Hello Tamim,
Thank you for your suggestion.
You can fork this repo to your account and make your change then create a pull requst.

**Comment by hmze123** [comment]
> Hey bro I have added uri support in the app and it supports direct uri links such as vmess,vless,trojan . I don't know much about github I'm new here. How can I upload the code ?
Can I talk to you on Telegram?
