### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by peyman007** [dev7dev/V2ray-Android#13]
Hello
Do you plan to update in the near future?
Thanks

**Comment by codewithtamim** [comment]
> Hello Do you plan to update in the near future? Thanks

What type of update bro?

**Comment by peyman007** [comment]
Update core

**Comment by peyman007** [comment]
> > Hello Do you plan to update in the near future? Thanks
> 
> What type of update bro?



> > Hello Do you plan to update in the near future? Thanks
> 
> What type of update bro?



> > Hello Do you plan to update in the near future? Thanks
> 
> What type of update bro?

Update core

**Comment by peyman007** [comment]
> > Hello Do you plan to update in the near future? Thanks
> 
> What type of update bro?

Update core

**Comment by dev7dev** [comment]
> Hello Do you plan to update in the near future? Thanks

Hi peman,
Yes, Sure.
I am working on a new update.
