### ISSUE TITLE
Updated Core to 1.8.7

### ISSUE THREAD

**Issue by codewithtamim** [dev7dev/V2ray-Android#14]
Hey bro. I updated the core to 1.8.7 and added support for all protocols now.
Now it supports also 
Socks
ShadowSocks

**Comment by hmze123** [comment]
> Hey bro. I updated the core to 1.8.7 and added support for all protocols now. Now it supports also Socks ShadowSocks

Share, brother, we are waiting

**Comment by dev7dev** [comment]
Hi tamim 
Thank you for your suggestion.
I am currently working on a new library update, that is more standard than the current version.
On the new update, uri support and the new version of xray will be added.
