### ISSUE TITLE
Many issues happening new update.

### ISSUE THREAD

**Issue by codewithtamim** [dev7dev/V2ray-Android#15]
Hi dev7,

I hope you're doing well. I'd like to discuss the recent update. I noticed that you've added URI support to the library, but it doesn't seem to work for protocols like Shadowsocks and SOCKS (with and without username/password authentication). Additionally, the download and upload traffic and speed indicators aren't functioning.

I had implemented support for all protocols in a straightforward manner and also implemented URI support in significantly fewer lines of code than you did. However, I'm unsure why you chose to modify the code to achive it . I took inspiration from V2Ray NG to add URI support, and it works seamlessly, supporting all protocols such as Vmess, Vless, Trojan, Shadowsocks, SOCKS, and even  added subnet masks.

Could you please address these issues? Should I submit a pull request or leave it as it is? Honestly, I chose to use this library because of its lightweight nature. However, with the new update, it seems to be a bit messy. Please consider resolving these issues. There are much simpler ways to handle this, buddy.

**Comment by dev7dev** [comment]
Hello Tamim,
I appreciate your attention.
The network speed and traffic counter bugs have been fixed in the last commit. I didn't notice your changes and adding uri support. Have you sent me a pull request?
However, I preferred to use a golang library to convert uri to json.
In the new update, I tried to put all the items in a classified manner and do everything in the library as much as possible to make it easier to use the library.
The program has not become heavier with more code and still does the same work as before. There were many crashes and ANRs in the previous version, which have been fixed in the new update.

**Comment by codewithtamim** [comment]
> Hello Tamim, I appreciate your attention. The network speed and traffic counter bugs have been fixed in the last commit. I didn't notice your changes and adding uri support. Have you sent me a pull request? However, I preferred to use a golang library to convert uri to json. In the new update, I tried to put all the items in a classified manner and do everything in the library as much as possible to make it easier to use the library. The program has not become heavier with more code and still does the same work as before. There were many crashes and ANRs in the previous version, which have been fixed in the new update.

Bro scocks and shadowsocks uri link don't  work on this library. I tested and it gives json parsing eception. And bro Im running production level app with this library with some of my modifications with uri support,all protocol support  and crash and anr fix.
Now you will be surprised that we have 99.98% crash free users !!!

**Comment by dev7dev** [comment]
Hi again tamim
Please send me your corrections.
I don't see your changes in your repositories!
And this version is without crashes. But if you see crashes or ANR, let me know.
This module also has a simple structure, and I am trying to solve the problems related to the parser. If you have a better solution, I would be happy to see it.
