### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by NotMeanttoBe** [dev7dev/V2ray-Android#17]
Brother, I used your software to connect but the connection was not successful. I am an xray server. This is my client configuration.
```json
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "xxxxxxxx",
            "port": xxxxxxxx,
            "users": [
              {
                "id": "ee00332e-c219-452c-8c6d-06289fa2a3f3",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                "flow": ""
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp"
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "enabled": true
      },
      {
        "type": "field",
        "ip": [
          "xxxxxxxx"
        ],
        "outboundTag": "proxy",
        "enabled": true
      }
    ]
  }
}
```
At present, my configuration can connect normally, but when I need to jump to visit some websites, or redirect to another path, it cannot be loaded. Can you help me solve it? Dude

**Comment by Anselaaa** [comment]
```json
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "xxxxxx",
            "port": xxxxx,
            "users": [
              {
                "id": "ee00332e-c219-452c-8c6d-06289fa2a3f3",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                "flow": ""
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp"
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "enabled": true
      },
      {
        "type": "field",
        "ip": [
          "xxxxxxx"
        ],
        "outboundTag": "proxy",
        "enabled": true
      }
    ]
  }
}
```
This is my new configuration,my configuration can connect normally, but when I need to jump to visit some websites, or redirect to another path, it cannot be loaded. Can you help me solve it? Dude

**Comment by dev7dev** [comment]
Hi ,
please give us more information. some logs or details.

**Comment by NotMeanttoBe** [comment]
![androidlog](https://github.com/dev7dev/V2ray-Android/assets/152356612/a2855d32-7029-4648-bb3d-aa458c91066e)

Hello, bro, this is my android studio log, I don't know why this happens, my configuration didn't have any problems before you updated to version 1.8.10. And when I used v2rayNG everything was fine

**Comment by dev7dev** [comment]
Hi again,
Clone new update and Decrease write byte size in  [clientOutStream](https://github.com/dev7dev/V2ray-Android/blob/2df16248bcf252045b86d79894e6393b35578a9a/v2ray/src/main/java/dev/dev7/lib/v2ray/services/V2rayVPNService.java#L235) to 42 and check it again.

**Comment by NotMeanttoBe** [comment]
Hello, brother. I tried the method you suggested by using clientOutStream.write(42);, but it didn't work. 
![1718071430247](https://github.com/dev7dev/V2ray-Android/assets/152356612/b46214c6-ab0b-48a1-84bf-c5bc0cd6b4e7)
![1718071449142](https://github.com/dev7dev/V2ray-Android/assets/152356612/b6ace014-0b48-47e3-8e3c-f4dd3510fc98)

**Comment by dev7dev** [comment]
What is your test device?
This is the problem with the xray wrapper.
https://github.com/2dust/AndroidLibXrayLite/blob/cdcd6e1d56b76b0750bb8f7bf7e5336abf078f83/libv2ray_support.go#L299
This wrapper is common to our module and v2rayNG. Check if the same log is registered in v2rayNG when connecting to the same configuration.

**Comment by NotMeanttoBe** [comment]
Hey buddy
I'm not very familiar with Go language code. Everything seems to be working fine in v2rayNG, and I haven't seen the same log messages. I'm not sure what to do next. I'm using a Xiaomi phone.

**Comment by dev7dev** [comment]
Do you have the same problem with another configuration?
What is the exact model of your test device? I have several Xiaomi phones for testing and the module works well.

**Comment by NotMeanttoBe** [comment]
Thank you for your response.
I am using Xiaomi 11 Pro and Oppo A1 Pro.
All my configurations are experiencing this issue (they can connect properly, but when I open the browser, I cannot access or redirect properly).
When I used your previous version 1.8.6, everything worked perfectly. However, with the current versions 1.8.10 and 1.8.13, I've encountered this problem on my devices and configurations. I reviewed your code but couldn't identify the issue. I suspect it might be related to modifications made to libv2ray.aar.
Could you please look into this? Thank you.

**Comment by dev7dev** [comment]
Does the connection test work for you?
Remove the rules part from your config and do a test again.

**Comment by NotMeanttoBe** [comment]
Thank you once again for your response. My rule configuration has been useful; however, even when I use the default settings without any additional rules, I still encounter the same issue.

**Comment by dev7dev** [comment]
Hi again,
please test latest commit.

**Comment by NotMeanttoBe** [comment]
Thank you, brother, I can use it normally now.

**Comment by NotMeanttoBe** [comment]
Would you consider developing an iOS project for connecting to v2ray in the future?

**Comment by dev7dev** [comment]
Writing a library for iOS requires more prerequisites.
Unfortunately, it is not possible to create an apple store developer account for me at the moment.
