### ISSUE TITLE
give a JSON object as a server instead of a string

### ISSUE THREAD

**Issue by farzinAndroid** [dev7dev/V2ray-Android#23]
Hi. I have JSON object that is coming from server and that is my server config and it changes to a ServerConfig Object in my app. I was wondering how i can give this kind of object to the library instead of a config String. I noticed you used a JSON object in the pictures but i dont know how to do that.Do i just turn the Object into a String? using Gson or other libraries?. Thanks in Advance.

**Comment by codewithtamim** [comment]
Images are from old library

**Comment by farzinAndroid** [comment]
So there is no way to do it?

**Comment by codewithtamim** [comment]
> So there is no way to do it?

There is actually. Just use the old releases of the library.

**Comment by dev7dev** [comment]
> Hi. I have JSON object that is coming from server and that is my server config and it changes to a ServerConfig Object in my app. I was wondering how i can give this kind of object to the library instead of a config String. I noticed you used a JSON object in the pictures but i dont know how to do that.Do i just turn the Object into a String? using Gson or other libraries?. Thanks in Advance.

All versions of this library support json as string.
