### ISSUE TITLE
does not work on android 9 and below

### ISSUE THREAD

**Issue by ydnikov** [dev7dev/V2ray-Android#24]
vpn icon appears in status bar, no notification, getConnectionState returns connected
does not load any site in the browser
on android 10 and above works perfectly

logcat on android 8:
![image](https://github.com/user-attachments/assets/31e767dc-a0f9-4468-a954-5fe403d7d45b)

**Comment by codewithtamim** [comment]
use min sdk as 21

**Comment by ydnikov** [comment]
I made minsdk = 21 in each build gradle file, it didn't help

**Comment by dev7dev** [comment]
Hi,
Please test latest commit.
There is some optimaization in vpn service.

**Comment by ydnikov** [comment]
it works, thank you very much
on the whole github this is the only library that is very easy to install and easy to use
the best and without competitors, thanks for the wonderful library
