### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by BroadcomArabia** [dev7dev/V2ray-Android#28]
Slow Speed

**Comment by dev7dev** [comment]
Hi,
Please explain more what made you open this issue.

**Comment by BroadcomArabia** [comment]
The Speed Is Slow, But I Have Fixed It

في الخميس، ٥ سبتمبر، ٢٠٢٤، ٦:٠٦ م Dev7 Developers ***@***.***>
كتب:

**Comment by BroadcomArabia** [comment]
But Now There Is Another Problem, Notification Status Not Updating On
Android 6.0

في الخميس، ٥ سبتمبر، ٢٠٢٤، ٦:٠٦ م Dev7 Developers ***@***.***>
كتب:
