### ISSUE TITLE
Are inbound/outbound objects necessary?

### ISSUE THREAD

**Issue by NavidShokoufeh** [dev7dev/V2ray-Android#5]
I tested your codes and i faced that it require us to put objects like : inbound , outbound , setting and etc.
are they necessary?

**Comment by dev7dev** [comment]
Hi,
In this module, the contents of the json file are directly delivered to the X-ray core.
These values may be required in some cases.
For more information, you can see the following repository:

[Xray-Example](https://github.com/XTLS/Xray-examples)

There are examples of json X-ray configuration in these, by comparing them, you can understand the performance of each component.
