### ISSUE TITLE
🔗 URI links

### ISSUE THREAD

**Issue by itsDantes** [dev7dev/V2ray-Android#8]
thanks for your work  👍 

please add ability to support URI links , because we should convert links to jSON every time.

**Comment by codewithtamim** [comment]
> thanks for your work 👍
> 
> please add ability to support URI links , because we should convert links to jSON every time.

I can add that bro !

**Comment by dev7dev** [comment]
> thanks for your work 👍
> 
> please add ability to support URI links , because we should convert links to jSON every time.

Hi,
You can use this python library to convert v2ray uri to json.
https://github.com/Am-Delta/v2ray-to-json
You can also understand the logic of converting v2ray uri`s to json from this library and implement it in Java.
We would appreciate it if you write a Java module to convert v2ray uri to json and commit it to this repository.
