### ISSUE TITLE
The app crashes in Andorid 14(Samsung S21 Ultra)

### ISSUE THREAD

**Issue by codewithtamim** [dev7dev/V2ray-Android#9]
The app crashes in Andorid 14(Samsung S21 Ultra)

**Comment by dev7dev** [comment]
Hello, 
Are you using the latest source (commit)?
In the last release, we solved the problems related to Android 14 and upgraded the target SDK to 34.
Please provide more information about the crash.

**Comment by codewithtamim** [comment]
> Hello, Are you using the latest source (commit)? In the last release, we solved the problems related to Android 14 and upgraded the target SDK to 34. Please provide more information about the crash.

Hi, Yes I have used the latest one. But it crashes like this.I have built a app for my client and he sent me the video.But it works fine in my android 14 virtual device.

https://github.com/dev7dev/V2ray-Android/assets/132823494/d9441ce3-0d38-4e30-985b-dc4fc891894f

I sent him both debug and signed apk but both didn't work.

**Comment by dev7dev** [comment]
In this video, there is no trace of the module.
Unfortunately, we cannot be sure of the problem until we see the correct crash log.
Our suggestion is to add Firebase Crashlytics to your application so that you can see crash details in Firebase console.

**Comment by codewithtamim** [comment]
> In this video, there is no trace of the module. Unfortunately, we cannot be sure of the problem until we see the correct crash log. Our suggestion is to add Firebase Crashlytics to your application so that you can see crash details in Firebase console.

Go your point  Thanks !.
